name: Release Please

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
  push:
    branches:
      - master

env:
  PRERELEASE: 'false'

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"deprecation","section":"Deprecations","hidden":false},{"type":"revert","section":"Reverts","hidden":false}]'
          release-type: 'node'
          default-branch: '${{ github.ref_name }}'
          package-name: '@blackbaud/skyux-design-tokens'
          pull-request-title-pattern: 'chore: release ${version}'
          labels: 'autorelease ${{ github.ref_name }}: pending'
          release-labels: 'autorelease ${{ github.ref_name }}: tagged'
          prerelease: ${{ env.PRERELEASE == 'true' }}
          draft-pull-request: true
          include-v-in-tag: false
          # BREAKING CHANGE only bumps semver minor if version < 1.0.0
          bump-minor-pre-major: true
          # feat commits bump semver patch instead of minor if version < 1.0.0
          bump-patch-for-minor-pre-major: true
          # Temporary for the first release so that old non-conventional commits do not enter CHANGELOG
          last-release-sha: 'c7561e8f0d28d75b9f345a3e56d9ec8dcc469c6a'
          token: '${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}'
