name: Validate pull request
on:
  pull_request_target:
    types:
      - edited
      - opened
      - reopened
      - synchronize

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  pull-requests: read

jobs:
  conventional-title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: amannn/action-semantic-pull-request@v5
        with:
          # subject should not start with a capital letter, include an exclamation point, or end with a period
          subjectPattern: ^(?![A-Z]).[^!]+(?<![.])$
          types: |
            feat
            fix
            refactor
            test
            build
            ci
            chore
            revert
            deprecation
          validateSingleCommit: true
          validateSingleCommitMatchesPrTitle: true
